title: "Dott. Umberto Serra - Medico Oculista"
description: "Dott. Umberto Serra - Medico Chirurgo Specialista in Oftalmologia"
baseurl: "/dottserra.com"
url: "https://emiliolodigiani.github.io"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      lang: "it"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - tailwind.config.js
  - README.md

plugins:
  - jekyll-seo-tag
